/*
 * This source file was generated by the Gradle 'init' task
 */
package com.athabasca;

import java.lang.reflect.Field;
import java.util.concurrent.CountDownLatch;

import javax.swing.JButton;
import javax.swing.SwingUtilities;

import org.junit.Test;

public class AppTest {
    @Test public void runApp() throws InterruptedException {
        CountDownLatch latch = new CountDownLatch(1);
        SwingUtilities.invokeLater(() -> {
            // Login login = new Login();
            // ClientList cl = new ClientList();
            // AssignClient ac = new AssignClient();
            TestFrame tf = new TestFrame();
            tf.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                    latch.countDown(); // Release the latch when the window is closed
                }
            });
        });
        latch.await();
    }
}
