/*
 * This source file was generated by the Gradle 'init' task
 */
package com.athabasca;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        new App();
    }
}
